### ISSUE TITLE
reading response content should not produce NullPointerException when there is no content

### ISSUE THREAD

**Issue by stefan-dimitrov** [clouway/chita#30]
When inputStream of the http response is *null* a NullPointerException is thrown when trying to read the response content.
Instead a value should be returned - perhaps *null*, an empty string or something else.

**Comment by mgenov** [comment]
It's related with #32 and fixed in #34 

The design is now throwing IOException when there is communication issue instead of returning dummy response.

**Comment by tsony-tsonev** [comment]
We can close this one i think.
