### ISSUE TITLE
chita/api: misleading message() method in HttpResponse

### ISSUE THREAD

**Issue by mgenov** [clouway/chita#5]
The HttpResponse object has misleading message() method. Probably this method should return returned response as string message or it can be removed and replaced with:

```java
String message = response.body(); 
```

**Comment by stefan-dimitrov** [comment]
The method actually returns the status message of the response, so that
- if status code is 200, then the status message is "OK";
- if status code is 404, then status message is "Not found.";
- ... etc, etc.

So maybe we should keep the method and rename it to `statusMessage` ?

**Comment by mgenov** [comment]
statusMessage sounds much better.

**Comment by stefan-dimitrov** [comment]
Ok, it shall be renamed.
